language: java
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
jdk:
  - oraclejdk8

install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -V -B

before_script:
  - docker run --env INFLUXDB_UDP_ENABLED=true --publish 127.0.0.1::8086 --publish 127.0.0.1::8089/udp --tmpfs /var/lib/influxdb:rw,noexec,nosuid,size=65536k --detach influxdb:1.3-alpine
  - sleep 2
  - docker ps
  - curl -v -XPOST 'http://localhost:8086/query' --data-urlencode 'q=CREATE DATABASE "influx4j"'

script:
  - mvn test -B -V
